#!/bin/bash

# Cores
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="ED-[1-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")
COMMIT_MESSAGE=$(cat "$1")

if [ -z "$ISSUE_ID" ]; then
    echo -e "${BRed}Branch não está no padrão que deveria mestre... ${NC}"
    read -p "Confirmar commit? [y/N]: " $confirm
    $confirm=$(echo $confirm | tr '[:lower:]' '[:upper:]')
    if [ $confirm -eq "N" ]; then
        exit 1
    fi
fi

# i.g. HEY-1: HEY-1: my feature
if [[ $COMMIT_MESSAGE == $ISSUE_ID* ]]; then
    exit 0
fi

echo "$ISSUE_ID $COMMIT_MESSAGE" >$1