#!/bin/bash


Rodar o phpstan no container
docker exec php8-projects sh -c "cd /var/www/html/gerenciador-compras && ./vendor/bin/phpstan analyze"
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
    exit 1;
fi;


# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")
for FILE in $STAGED_FILES
do
    docker exec php8-projects sh -c "cd /var/www/html/gerenciador-compras && ./vendor/bin/pint '${FILE}'"
    git add "${FILE}";
done;

exit 0;
